version: 2

project_name: vic-ptv-cli

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: bls
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: "https://github.com/bls/vic-ptv-cli"
    description: "CLI for the Public Transport Victoria (PTV) Timetable API"
    license: "MIT"
    install: |
      bin.install "vic-ptv-cli"
    test: |
      system "#{bin}/vic-ptv-cli", "--help"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
